### ISSUE TITLE
Doctrine version

### ISSUE THREAD

**Issue by ruslan-polutsygan** [AliHichem/AliDatatableBundle#110]
Hi

Is there any particular reason to restrict `doctrine/orm` version to `<2.5`?

Thanks

**Comment by AliHichem** [comment]
as this is a syfmony2 bundle, it make more sense to make it's requirements matches with symfony2 vendors requirement and for now the current stable version of symfony2 is 2.6 which still require doctrine <2.5

**Comment by ruslan-polutsygan** [comment]
Hi,

Thanks for reply.

"Symfony standard edition" is just a project boilerplate. It recommends `orm` < 2.5, but doesn't forbids me to update root `composer.json` file - it is not in the `vendor` dir. 

From perspective, if your bundle depends on some version specific feature/behavior - then ok, it makes sense to restrict it. But if doesn't - then you don't allow to use latest doctrine stable version. 

I believe it's up to end application developer to decide whichever lib version to use. If end app doesn't work because of bad configured dependencies - it is developer's problem. 

Please confirm that you are not going to update the bundle dependencies. Thanks.

**Comment by AliHichem** [comment]
This bundle does not depend on doctrine/orm < 2.5 or at least this is what I'm assuming because I still didn't work with doctrine >= 2.5. I understand your concern but as far as I see in doctrine repo the version 2.5.0 is still not stable and they are still preparing to make a stable release of it, plus I left the issue open for about two days no one supported your request because I guess most developers still work with 2.4.x versions.

About "how" to take a decision with which version of the package should the bundles go, I do not agree with your analogy : doctrine/orm 2.5 didn't even exist when this bundle was created so I can't predict what changes the 2.5 can bring and whether this bundle is still compatible or not .. same for twig and symfony . "If" it is  the developer decision to choose the versions of the external bundles requirement then why the requirement section exist anyway ?

Anyway I'm not against changing the requirements to <= 2.5, I guess you already used this bundle with the 2.5 version of doctrine/orm. If you can confirm that this bundle works fine with that doctrine version then yes I'll do the tests this week and change the requirements.

**Comment by ruslan-polutsygan** [comment]
What do yo mean 2.5.0 is not stable?
https://github.com/doctrine/doctrine2/releases - v2.5.0 released on Apr 2
https://packagist.org/packages/doctrine/orm#v2.5.0 - published package

Yes, I'm working with doctrine 2.5
I didn't check all possible use cases, but what I need works just fine - datatable gets rendered and paginated well.

Thanks

**Comment by AliHichem** [comment]
I'll try to make tour on testing it and update the requirement this weekend.
