### ISSUE TITLE
Send extra parameters in data object to server

### ISSUE THREAD

**Issue by webkod3r** [AliHichem/AliDatatableBundle#111]
Hi, I wanna know if there is a way to send extra parameters in AJAX call when datatable fetch data from server. 
In standalone datatable plugin I can do this:

```js
"ajax": {
      url: Routing.generate('app_units_datatable', {id: 1}),
      data: function (d) {
        d.year = $('#year').val();
        d.provider = $('#provider').val();
      }
    },
```

Thanks in advance.
Greetings 
WK

**Comment by AliHichem** [comment]
Currently extra parameters are not supported, it can be added but the integration of datatable that this bundle does tends to be "simplistic" and allow mostly integration with doctrine itself, the jquery datatable plugin has a lot of features and including them to this bundle will require a lot of work which is not the purpose here..

**Comment by webkod3r** [comment]
Well, using DataTable API I found the way to send extra parameters to server in AJAX call.

```js
// get api instance
var dtLogs = $('#dtLogs').DataTable();

//Extra filter values
var queryObj = new Object();
queryObj.start = $('#start').datepicker('getDate');
queryObj.finish = $('#finish').datepicker('getDate');
queryObj.level = $('#level').val();

// create query string
var queryString = $.param(queryObj);

// load data using api
dtLogs.ajax.url(Routing.generate('system_logs_grid') + '?' + queryString).load();
```

and that's all. Tested and work perfectly. Then in php controller build the query with `DataTable`'s `QueryBuilder`

```php
private function _datatable(){
    ...
    /**
     * @var $qb \Doctrine\ORM\QueryBuilder
     */
    $qb = $datatable->getQueryBuilder()->getDoctrineQueryBuilder();

    $tmp = $request->query->get('start');
    if( isset($tmp) ){
        $d = \DateTime::createFromFormat('Y-m-d', $tmp);
        $qb->andWhere('x.createdAt >= :startDate')->setParameter('startDate', $d);
    }

    $tmp = $request->query->get('finish');
    if( isset( $tmp ) ){
        $d = \DateTime::createFromFormat('Y-m-d', $tmp);
        $qb->andWhere('x.createdAt <= :endDate')->setParameter('endDate', $d);
    }

    $tmp = $request->query->get('level');
    if( isset( $tmp ) ){
        $qb->andWhere('x.level = :level')->setParameter('level', $tmp);
    }

    return $datatable;
}
```

**Comment by AliHichem** [comment]
When I said "...Currently extra parameters are not supported..." I was referring to this bundle and I was not talking about jquery datatable. Also what you did might work for you but the code you wrote can't unfortunately be used since it's not generic : all what you wrote should be transparent to the end developer and he shouldn't make all of these changes on his own, by following the logic of this bundle the extra parameters should be added by a simple call to 'datatable' service like this 
```
->get('datatable')
->addExtraParameters([
    'param1' => 'value1',
    'param2' => 'value2',
    ...
]]
```
As a matter of fact there is no plan to add this feature for now, you still can make a pull request if you want of course after converting what you did to be compatible with this bundle.
