### ISSUE TITLE
Errors in Spanish translation file

### ISSUE THREAD

**Issue by migmolrod** [AliHichem/AliDatatableBundle#134]
I've noticed that special characters in our language (eg, vowels with acute accents like á and É) are missing in Resources/translations/messages.es.yml file.
Something to do with character encoding? Or maybe an error in the text editor?
I can fork and PR a corrected version if you want to see if that helps.

**Comment by AliHichem** [comment]
It's not an encoding issue, it's just that those special character are not used at all in the translated text. It would be great if you can help us have those special characters integrated in the Spanish translated file so please feel free to make a pull request and I'll accept it .

**Comment by migmolrod** [comment]
Done.
I must point out something, however. DataTables already has a i18n feature and maybe the bundle can use it. We're repeating something that is already done and we, users of Symfony2, really hate to reinvent the wheel, do we? :)

The thing would be to 'guess' which language file to include from dataTables 'language' property/configuration given a locale inside Symfony2. Not sure how hard or easy this can be.

**Comment by AliHichem** [comment]
Thanks for the note but this is not "reinventing the wheel" since the translation files has attributes proper to this bundle like "action", "confirm_delete" ,"delete" and so. This is due to the fact that this bundle does not include all the features of the jQuery bundle since this is not the purpose of this project, we're just making it easy to integrate jquery datatable into a symfony2 project for simple use cases, although we're adding other features proper to this bundle which focuses mostly on the backend and server side processing. 

To get the full package of feature of jQuery Datatable I'm afraid you still need to make the integration manually.

I appreciate your concern but the coming upgrade has different purposes , for instance we're planning on adding "mongodb" and "elasticsearch" drivers to this bundle. Since I'm extremely busy with my work it's not obvious to finish the mongodb integration and add the elasticsearch driver as well. Any contribution in this direction would be more than appreciated !
