### ISSUE TITLE
Function Test Datatable Conflict

### ISSUE THREAD

**Issue by apatkinson** [AliHichem/AliDatatableBundle#72]
I am trying to test pages that have a datatable on them with the phpUnit functional test.

The first view of the datatable is fine, but the second view **always** causes the exception:

```
Identifer already exists
```

Even if the test classes are different.
Is there a known workaround for this?

I am not testing the datatable directly, it just happens to be on the same page, and the service creates it.

**Comment by rbaarsma** [comment]
@apatkinson Did you ever find a solution to this?

I actually don't think this is a Datatable bug, but something missing in PHPunit testing. It uses the same client throughout your test and this may cause problems with services such as the datatable (although I've never seen any other bugs like this). Probably re-creating the client would do the trick.. but I also don't know what a better solution would be..

**Comment by rbaarsma** [comment]
After some researching for a good solution and looking into the Datatable code, our conclusion is as follows:

- In Datatable.php there is a static array of instances. This seems to us as bad code that has no actual use. In Symfony 2 a service is already a singleton and there seems to be reason to create and keep track of instances statically.
- the only code using the static instances array is the DatatableTest and the AliDatatableExtension. At least the DatatableExtension should simply have the datatable service injected and there seems no reason to statically refer to a specific instance. Obviously if it's no longer needed to have this code the test should also no longer use it.

Our workaround to this problem is extending the Datatable service with our own class and creating a public static function clearInstances() that simply sets _instances to an empty array. Still not a very nice solution, but at least our tests are not throwing errors anymore

**Comment by apatkinson** [comment]
Seems like a feasible solution. Looking back the PR I can see we swapped out to a headed browser test with Selenium. The random identifier was not a good solution for us.

**Comment by greg606** [comment]
same with Behat
